### ISSUE TITLE
about reproduction

### ISSUE THREAD

**Issue by izumiakitoshi** [frednam93/FilterAugSED#1]
Thank you for disclosing your python script!
I want to reproduce your result of technical paper.

In the paper of Table2, you produced four modeles.
I think "config.yaml" on github is for model No 1.
How can I reproduce model No 2,3,4 ?

Best regards

**Comment by frednam93** [comment]
Thanks for your interest! I have uploaded other configuration files. Please refer to reademe/training/other model settings.

Regards,
